# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaBaru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x1', models.SmallIntegerField()),
                ('x2', models.SmallIntegerField()),
                ('x3', models.SmallIntegerField()),
                ('x4', models.SmallIntegerField()),
                ('x5', models.SmallIntegerField()),
                ('x6', models.SmallIntegerField()),
                ('x7', models.SmallIntegerField()),
                ('x8', models.SmallIntegerField()),
                ('x9', models.SmallIntegerField()),
                ('beasiswa', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'siswa_baru_beasiswa',
            },
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'ordering': ['id']},
        ),
    ]
