# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_auto_20170510_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={'ordering': ['nomer']},
        ),
        migrations.AddField(
            model_name='siswa',
            name='jarak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nomer',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x1',
            field=models.SmallIntegerField(choices=[(b'1', b'Ada'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x2',
            field=models.SmallIntegerField(choices=[(b'1', b'Ada'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x3',
            field=models.SmallIntegerField(choices=[(b'3', b'1'), (b'2', b'2'), (b'1', b'3')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x4',
            field=models.SmallIntegerField(choices=[(b'2', b'Ada'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x5',
            field=models.SmallIntegerField(choices=[(b'4', b'Ada'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x6',
            field=models.SmallIntegerField(choices=[(b'4', b'Ada'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x7',
            field=models.SmallIntegerField(choices=[(b'0', b'Ada'), (b'4', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x8',
            field=models.SmallIntegerField(choices=[(b'4', b'450 VA'), (b'3', b'900 VA'), (b'2', b'1300 VA'), (b'1', b'2200 VA'), (b'0', b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x9',
            field=models.SmallIntegerField(choices=[(b'3', b'1'), (b'2', b'2'), (b'1', b'3'), (b'0', b'>3')]),
        ),
    ]
