# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_auto_20170531_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswabaru',
            name='x1',
            field=models.SmallIntegerField(choices=[(1, b'Ada'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x2',
            field=models.SmallIntegerField(choices=[(1, b'Ada'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x3',
            field=models.SmallIntegerField(choices=[(3, b'1'), (2, b'2'), (1, b'3')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x4',
            field=models.SmallIntegerField(choices=[(2, b'Ada'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x5',
            field=models.SmallIntegerField(choices=[(4, b'Ada'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x6',
            field=models.SmallIntegerField(choices=[(4, b'Ada'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x7',
            field=models.SmallIntegerField(choices=[(0, b'Ada'), (4, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x8',
            field=models.SmallIntegerField(choices=[(4, b'450 VA'), (3, b'900 VA'), (2, b'1300 VA'), (1, b'2200 VA'), (0, b'Tidak Ada')]),
        ),
        migrations.AlterField(
            model_name='siswabaru',
            name='x9',
            field=models.SmallIntegerField(choices=[(3, b'1'), (2, b'2'), (1, b'3'), (0, b'>3')]),
        ),
    ]
